### ISSUE TITLE
Error downloading on windows 10

### ISSUE THREAD

**Issue by alkorang** [juj/emsdk#134] opened 2018-02-23 12:41 UTC
```powershell
PS C:\Users\alkorang\.emsdk> .\emsdk.bat install latest
Installing SDK 'sdk-1.37.34-64bit'..
Installing tool 'clang-e1.37.34-64bit'..
The contents of file 'llvm/tag/win_64bit/emscripten-llvm-e1.37.34.zip' already exist in destination 'C:/Users/alkorang/.emsdk/clang/e1.37.34_64bit', skipping.
Done installing tool 'clang-e1.37.34-64bit'.
Installing tool 'node-8.9.1-64bit'..
The contents of file 'node-v8.9.1-win-x64.zip' already exist in destination 'C:/Users/alkorang/.emsdk/node/8.9.1_64bit', skipping.
Done installing tool 'node-8.9.1-64bit'.
Installing tool 'python-2.7.5.3-64bit'..
The contents of file 'python_2.7.5.3_64bit.zip' already exist in destination 'C:/Users/alkorang/.emsdk/python/2.7.5.3_64bit', skipping.
Done installing tool 'python-2.7.5.3-64bit'.
Installing tool 'java-8.152-64bit'..
The contents of file 'portable_jre_8_update_152_64bit.zip' already exist in destination 'C:/Users/alkorang/.emsdk/java/8.152_64bit', skipping.
Done installing tool 'java-8.152-64bit'.
Installing tool 'emscripten-1.37.34'..
Error downloading URL 'https://github.com/kripken/emscripten/archive/1.37.34.zip': <urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version>
Installation failed!
PS C:\Users\alkorang\.emsdk>
```

I tried download the file from https://github.com/kripken/emscripten/archive/1.37.34.zip using my web browser and it worked perfect.
I used `emsdk-portable-64bit.zip` from https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html

**Comment by alkorang** [comment] 2018-02-23 13:07
I found a way to work around this problem. I downloaded the zip file through my web browser and copied it into `zips` directory.

**Comment by brion** [comment] 2018-02-25 13:44
The problem is that the bundled Python is pretty old and includes outdated libraries, so it's using an old SSL/TLS version that's incompatible with how GitHub now configures their servers.

I can confirm it works running `emsdk` through a newer system Python, such as:

```
python ./emsdk install latest
```

instead of

```
./emsdk.bat install latest
```

to bypass the old embedded python.

**Comment by brion** [comment] 2018-02-25 13:45
Same issue as https://github.com/juj/emsdk/issues/133

**Comment by juj** [comment] 2018-02-28 07:39
Fixed in https://github.com/juj/emsdk/commit/4c8ea1b10be7ab59ec0bb5a63934372cb4c2bcff

**Closed by juj** 2018-02-28 07:39 UTC
